FROM nvidia/cuda:12.2.2-runtime-ubuntu22.04
WORKDIR /app
RUN apt update && apt install -y python3 python3-pip libpq-dev
COPY streaming/consumer.py /app/streaming/consumer.py
COPY features/ /app/features/
RUN pip install kafka-python psycopg2-binary pandas numpy lightgbm
CMD ["python3", "streaming/consumer.py"]
