FROM nvidia/cuda:12.2.2-runtime-ubuntu22.04
WORKDIR /app
RUN apt update && apt install -y python3 python3-pip
COPY streaming/producer.py /app/streaming/producer.py
RUN pip install kafka-python numpy
CMD ["python3", "streaming/producer.py"]
