FROM nvidia/cuda:12.2.2-runtime-ubuntu22.04
WORKDIR /app
RUN apt update && apt install -y python3 python3-pip
COPY inference/api.py /app/inference/api.py
COPY features/ /app/features/
RUN pip install fastapi uvicorn pandas numpy lightgbm psycopg2-binary
CMD ["uvicorn", "inference.api:app", "--host", "0.0.0.0", "--port", "8000"]
